# deployment/flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: secure-devsecops-mini-proj-service
spec:
  selector:
    app: secure-devsecops-mini-proj
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort
